### ISSUE TITLE
求大佬赐法宝

### ISSUE THREAD

**Issue by yyt231** [moyuwa/toppwdhash#1]
大佬，干入门渗透的时候，您正在组件零组，两年过去了，零组经历了风风雨雨，而我依旧是一个渗透门外汉。现在有想重走渗透之路，问一下，能赐给我一份零组的资料吗

**Comment by moyuwa** [comment]
我没参与零组哈，也没有文库，其实我个人比较懒散的，渗透要有耐心，一个个小点摸排过去，慢慢有经验就好了
